apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzastore
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pizzastore
  template:
    metadata:
      labels:
        app: pizzastore
    spec:
      containers:
      - name: pizzastore
        image: gcr.io/gke-proj-1-394220/pizzastore-backend:v1.88
        ports:
        - containerPort: 5000