apiVersion: v1
kind: Service
metadata:
  name: pizzastore-fr
spec:
  selector:
    app: pizzastore-fr
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  # type: LoadBalancer
  type: NodePort